# Breast Cancer Coimbra
# DecisionTreeClassification

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

## Importing dataset

In [2]:
dataset = pd.read_csv('dataR2.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
dataset.isnull().sum() # Checking & finding the missing values of dataset 

Age               0
BMI               0
Glucose           0
Insulin           0
HOMA              0
Leptin            0
Adiponectin       0
Resistin          0
MCP.1             0
Classification    0
dtype: int64

## Splitting dataset into the Training Set and Test Set

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.31, random_state=0)

In [5]:
print(X_train)

[[8.60000000e+01 2.71800000e+01 1.38000000e+02 1.99100000e+01
  6.77736400e+00 9.02800000e+01 1.41100000e+01 4.35000000e+00
  9.00900000e+01]
 [4.90000000e+01 2.97777778e+01 7.00000000e+01 8.39600000e+00
  1.44970933e+00 5.13387000e+01 1.07317400e+01 2.07680100e+01
  6.02486000e+02]
 [6.60000000e+01 2.65625000e+01 8.90000000e+01 6.52400000e+00
  1.43223547e+00 1.49084000e+01 8.42996000e+00 1.49192200e+01
  2.69487000e+02]
 [4.40000000e+01 2.78876171e+01 9.90000000e+01 9.20800000e+00
  2.24859360e+00 1.26757000e+01 5.47817000e+00 2.30330600e+01
  4.07206000e+02]
 [8.20000000e+01 3.12174818e+01 1.00000000e+02 1.80770000e+01
  4.45899333e+00 3.16453000e+01 9.92365000e+00 1.99468700e+01
  9.94316000e+02]
 [5.10000000e+01 2.28928200e+01 1.03000000e+02 2.74000000e+00
  6.96142667e-01 8.01630000e+00 9.34977500e+00 1.15549200e+01
  3.59232000e+02]
 [6.60000000e+01 3.14465409e+01 9.00000000e+01 9.24500000e+00
  2.05239000e+00 4.59624000e+01 1.03552600e+01 2.33819000e+01
  1.10211000e+03]
 [6.40

In [6]:
print(y_train)

[2 2 2 2 2 2 1 1 1 2 2 2 2 1 1 2 1 1 1 1 1 2 1 1 1 2 2 2 1 1 1 2 1 1 1 2 2
 2 2 1 2 1 2 1 1 1 2 2 2 2 2 2 1 2 2 2 1 1 2 2 1 2 1 2 2 1 2 2 2 2 1 1 2 1
 2 2 2 2 1 1]


In [7]:
print(X_test)

[[3.40000000e+01 2.14700000e+01 7.80000000e+01 3.46900000e+00
  6.67435600e-01 1.45700000e+01 1.31100000e+01 6.92000000e+00
  3.54600000e+02]
 [4.60000000e+01 2.22100000e+01 8.60000000e+01 3.69400000e+01
  7.83620533e+00 1.01600000e+01 9.76000000e+00 5.68000000e+00
  3.12000000e+02]
 [5.40000000e+01 2.42187500e+01 8.60000000e+01 3.73000000e+00
  7.91257333e-01 8.68740000e+00 3.70523000e+00 1.03445500e+01
  6.35049000e+02]
 [7.70000000e+01 2.59000000e+01 8.50000000e+01 4.58000000e+00
  9.60273333e-01 1.37400000e+01 9.75326000e+00 1.17740000e+01
  4.88829000e+02]
 [7.60000000e+01 2.38000000e+01 1.18000000e+02 6.47000000e+00
  1.88320133e+00 4.31100000e+00 1.32513200e+01 5.10420000e+00
  2.80694000e+02]
 [8.60000000e+01 2.66666667e+01 2.01000000e+02 4.16110000e+01
  2.06307338e+01 4.76470000e+01 5.35713500e+00 2.43701000e+01
  1.69844000e+03]
 [5.20000000e+01 3.08012487e+01 8.70000000e+01 3.02120000e+01
  6.48349520e+00 2.92739000e+01 6.26854000e+00 2.42459100e+01
  7.64667000e+02]
 [4.00

In [8]:
print(y_test)

[1 2 2 1 1 2 2 2 2 2 1 1 2 1 1 2 1 2 2 2 1 1 1 2 2 2 2 2 1 2 1 1 1 1 1 2]


## Feature Scaling

In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [10]:
#print(X_train)

In [11]:
#print(X_test)

## Training "Decision Tree" model on the Training set

In [12]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion='entropy', random_state=0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [13]:
from sklearn.model_selection import cross_val_score, KFold

#for name, model in models:
#     kFold = KFold(n_splits=10)
accuracies = cross_val_score(classifier, X = X_train, y = y_train, cv = 10, scoring='accuracy')
print("Accuracy: {:.2f} %".format(accuracies.mean()*100), 
      "Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 72.50 % Standard Deviation: 17.50 %


## Predicting a new result

In [14]:
# print(classifier.predict(sc.transform([[feature-1, feature-2, ... , feature-n]])))

## Predicting the Test set results

In [15]:
y_pred = classifier.predict(X_test)

print('y_pred: ' + '\n', y_pred)
print('\n')

#reshape from "1 x length of column" to "length of column x 1" 
print('y_pred+y_test: '+'\n', np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),axis=1))

y_pred: 
 [1 2 1 1 2 2 1 1 1 2 2 1 2 1 1 2 1 1 1 1 2 1 2 2 2 2 2 1 2 2 2 2 2 2 1 2]


y_pred+y_test: 
 [[1 1]
 [2 2]
 [1 2]
 [1 1]
 [2 1]
 [2 2]
 [1 2]
 [1 2]
 [1 2]
 [2 2]
 [2 1]
 [1 1]
 [2 2]
 [1 1]
 [1 1]
 [2 2]
 [1 1]
 [1 2]
 [1 2]
 [1 2]
 [2 1]
 [1 1]
 [2 1]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [1 2]
 [2 1]
 [2 2]
 [2 1]
 [2 1]
 [2 1]
 [2 1]
 [1 1]
 [2 2]]


## Making the Confusion Matrix

In [16]:
from sklearn.metrics import confusion_matrix, classification_report
cm = confusion_matrix(y_test, y_pred)
cr = classification_report(y_test, y_pred)
print(cm)
print(cr)

[[ 8  9]
 [ 8 11]]
              precision    recall  f1-score   support

           1       0.50      0.47      0.48        17
           2       0.55      0.58      0.56        19

    accuracy                           0.53        36
   macro avg       0.53      0.52      0.52        36
weighted avg       0.53      0.53      0.53        36

